version: '3.8'

services:
  backend:
    build: .
    image: carbonexia-app
    container_name: carbonexia_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/carbonexia
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=changethis_secret_key_for_dev
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
      - redis
    networks:
      - carbonexia_net

  worker:
    image: carbonexia-app
    container_name: carbonexia_worker
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/carbonexia
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - carbonexia_net

  db:
    image: timescale/timescaledb:latest-pg14
    container_name: carbonexia_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carbonexia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carbonexia_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: carbonexia_redis
    ports:
      - "6379:6379"
    networks:
      - carbonexia_net

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - carbonexia_net

# volumes:
#   postgres_data:
volumes:
  postgres_data:

networks:
  carbonexia_net:
    driver: bridge
